spring:
  application:
    name: domain
  datasource:
    dynamic:
      hikari:
        connection-test-query: select 1
      primary: write
      strict: false
  profiles:
    active: dev
logging:
  level:
    com:
      licon:
        domain: debug
  config: classpath:logback-spring.xml

knife4j:
  enable: true

