spring:
  application:
    name: domain
  datasource:
    dynamic:
      hikari:
        connection-test-query: select 1
      primary: write
      strict: false
  profiles:
    active: pro
logging:
  level:
    com:
      licon:
        domain: debug
  config: classpath:logback-spring.xml

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true

decorator:
  datasource:
    enabled: false


