server:
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: LJ
    password: Qwe#1234
    url: jdbc:mysql://121.89.203.197:3306/ez_code?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&
      nullCatalogMeansCurrent=true