server:
  port: 8081
spring:
  profiles:
    active: dev
  application:
    name: workflow
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true
    async-executor-activate: false
logging:
  level:
    com:
      licon: debug
    org:
      activiti:
        engine:
          impl:
            persistence:
              entity: debug
  config: classpath:logback-spring.xml