spring:
  application:
    name: admin-core
  datasource:
    dynamic:
      hikari:
        connection-test-query: select 1
      primary: write
      strict: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

logging:
  level:
    com:
      licon:
        domain: debug
  config: classpath:logback-spring.xml

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true

decorator:
  datasource:
    enabled: false

pagehelper:
  params: pageNum=page;pageSize=pageSize;
  helper-dialect: mysql
  auto-dialect: true
  supportMethodsArguments: true


