spring:
  datasource:
    dynamic:
      hikari:
        connection-test-query: select 1
      primary: write
      strict: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml

knife4j:
  enable: true

decorator:
  datasource:
    enabled: false

pagehelper:
  params: pageNum=page;pageSize=pageSize;
  helper-dialect: mysql
  auto-dialect: true
  supportMethodsArguments: true


